name: Deployment
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build in Docker
        run: docker-compose up --build
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          # https://github.com/marketplace/actions/deploy-to-github-pages#using-an-ssh-deploy-key-
          # https://medium.com/@cmichel/how-to-deploy-a-create-react-app-with-github-actions-5e01f7a7b6b
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
